export const REQUEST_POSTS_IMAGE = 'REQUEST_POSTS_IMAGE'
export const RECEIVE_POSTS_IMAGE = 'RECEIVE_POSTS_IMAGE'
export const RECEIVE_POSTS_NOW_PLAYING = 'RECEIVE_POSTS_NOW_PLAYING'
export const REQUEST_POSTS_NOW_PLAYING = 'REQUEST_POSTS_NOW_PLAYING'
export const REQUEST_POSTS_COMING_SOON = 'REQUEST_POSTS_COMING_SOON'
export const RECEIVE_POSTS_COMING_SOON = 'RECEIVE_POSTS_COMING_SOON'

